os:
  - linux

language: php

php:
  - '7.1'

before_script:
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate
  - php artisan cache:clear
  - php artisan config:clear

script:
  - vendor/bin/phpunit --coverage-text