os:
  - linux

language: php

php:
  - '7.2'

before_script:
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --no-interaction
  - php artisan cache:clear --no-interaction
  - php artisan config:clear --no-interaction

script:

branches:
  only:
    - production
